"""Synthetic prediction, model interpretation and support-constrained Pareto comparison.

The demonstration is fully self-contained: every input record is generated by
:func:`synthetic_data` from deliberately invented formulas, so no private factory
record, frozen model or manuscript number is ever read.
"""

from __future__ import annotations

import hashlib
import json
import time
from dataclasses import asdict, dataclass
from datetime import UTC, datetime
from importlib.metadata import version
from pathlib import Path
from typing import Any

import numpy as np
import pandas as pd
from pymoo.algorithms.moo.moead import ParallelMOEAD
from pymoo.algorithms.moo.nsga2 import NSGA2
from pymoo.algorithms.moo.spea2 import SPEA2
from pymoo.core.problem import Problem
from pymoo.indicators.hv import HV
from pymoo.operators.crossover.sbx import SBX
from pymoo.operators.mutation.pm import PM
from pymoo.operators.sampling.lhs import LHS
from pymoo.optimize import minimize
from pymoo.util.ref_dirs import get_reference_directions
from sklearn.base import clone
from sklearn.dummy import DummyRegressor
from sklearn.ensemble import ExtraTreesRegressor, RandomForestRegressor, StackingRegressor
from sklearn.impute import SimpleImputer
from sklearn.inspection import permutation_importance
from sklearn.linear_model import HuberRegressor, Ridge
from sklearn.metrics import mean_absolute_error, r2_score, root_mean_squared_error
from sklearn.model_selection import KFold, train_test_split
from sklearn.neighbors import NearestNeighbors
from sklearn.pipeline import make_pipeline
from sklearn.preprocessing import PolynomialFeatures, StandardScaler

# Model inputs, engineered calendar features, prediction targets and decision variables.
CONTINUOUS = ["Q", "COD", "TN_in", "NH3N", "T", "PPA", "DO", "MLSS"]
FEATURES = ["doy_sin", "doy_cos", "trend", *CONTINUOUS]
TARGETS = ["TN_out", "DEC"]
ACTIONS = ["PPA", "DO"]
CONTEXT = ["Q", "COD", "TN_in", "NH3N", "T", "MLSS"]

# Length of the trailing input window: mean(x[t-1], x[t-2], x[t-3]).
ROLLING_WINDOW = 3
# Gregorian mean year, so the seasonal terms stay aligned across leap days.
DAYS_PER_YEAR = 365.2425
# Every 79th row loses its DO reading, which exercises fold-fitted imputation.
MISSING_STRIDE = 79
# Observation noise standard deviations of the two invented generating equations.
TN_OUT_NOISE_SD = 0.10
DEC_NOISE_SD = 80.0

SEARCH_METHODS = ("NSGA2", "SPEA2", "MOEAD", "UniformRandom")
# Hypervolume reference point, shared by every method on the normalised objective scale.
HV_REFERENCE_POINT = np.array([1.1, 1.1])


@dataclass(frozen=True)
class Settings:
    """Validated run configuration for the synthetic demonstration."""

    seed: int = 17
    rows: int = 480
    evaluations: int = 256
    optimizer_seeds: tuple[int, ...] = (11, 23, 37)
    scenarios: int = 3

    def __post_init__(self) -> None:
        if type(self.seed) is not int or not 0 <= self.seed <= 10_000_000:
            raise ValueError("Invalid seed.")
        if type(self.rows) is not int or not 180 <= self.rows <= 2000:
            raise ValueError("rows must be between 180 and 2000.")
        if (
            type(self.evaluations) is not int
            or not 64 <= self.evaluations <= 4096
            or self.evaluations % 32
        ):
            raise ValueError("evaluations must be a multiple of 32 in [64, 4096].")
        if not 1 <= self.scenarios <= 6:
            raise ValueError("scenarios must be between 1 and 6.")
        if not self.optimizer_seeds or len(set(self.optimizer_seeds)) != len(self.optimizer_seeds):
            raise ValueError("Optimizer seeds must be nonempty and unique.")


def canonical(value: Any) -> bytes:
    """Serialise ``value`` to the canonical UTF-8 JSON byte form used for hashing."""
    return json.dumps(value, ensure_ascii=False, sort_keys=True, allow_nan=False).encode("utf-8")


def sha(path: Path) -> str:
    """Return the SHA-256 hex digest of a file's bytes."""
    return hashlib.sha256(path.read_bytes()).hexdigest()


def synthetic_data(rows: int, seed: int) -> pd.DataFrame:
    """Generate the synthetic daily record set.

    Every range, coefficient and noise scale below is invented for this
    demonstration; none of it is derived from, or an anonymised copy of, the
    protected factory records.
    """
    rng = np.random.default_rng(seed)
    width = rows + ROLLING_WINDOW
    raw = pd.DataFrame(
        {
            "Q": rng.uniform(15000, 25000, width),
            "COD": rng.uniform(100, 300, width),
            "TN_in": rng.uniform(15, 40, width),
            "NH3N": rng.uniform(10, 30, width),
            "T": 20
            + 6 * np.sin(2 * np.pi * np.arange(width) / DAYS_PER_YEAR)
            + rng.normal(0, 1, width),
            "PPA": rng.uniform(300, 900, width),
            "DO": rng.uniform(1.3, 2.9, width),
            "MLSS": rng.uniform(3000, 5000, width),
        }
    )
    frame = raw.shift(1).rolling(ROLLING_WINDOW, min_periods=ROLLING_WINDOW).mean()
    frame = frame.iloc[ROLLING_WINDOW:].copy()
    frame.insert(0, "Date", pd.date_range("2000-01-04", periods=rows))

    day_of_year = frame.Date.dt.dayofyear.to_numpy()
    frame["doy_sin"] = np.sin(2 * np.pi * day_of_year / DAYS_PER_YEAR)
    frame["doy_cos"] = np.cos(2 * np.pi * day_of_year / DAYS_PER_YEAR)
    frame["trend"] = np.arange(rows)

    # TN_out falls with warmer, better-aerated and less loaded operation; the PPA
    # term is quadratic, which creates a genuine trade-off against the DEC objective.
    frame["TN_out"] = (
        7
        + 0.12 * (frame.TN_in - 25)
        - 0.12 * (frame["T"] - 20)
        + 0.0002 * (frame.MLSS - 4000)
        + 0.0012 * (frame.PPA - 600)
        - 0.6 * (frame.DO - 2)
        + 0.000002 * (frame.PPA - 600) ** 2
        + rng.normal(0, TN_OUT_NOISE_SD, rows)
    )
    # DEC rises with flow, sludge inventory, aeration intensity and PPA.
    frame["DEC"] = (
        8500
        + 0.08 * (frame.Q - 20000)
        + 0.45 * (frame.MLSS - 4000)
        + 500 * (frame.DO - 2)
        + 0.006 * (frame.PPA - 550) ** 2
        + rng.normal(0, DEC_NOISE_SD, rows)
    )

    frame.loc[frame.index[::MISSING_STRIDE], "DO"] = np.nan
    return frame.reset_index(drop=True)


def splits(rows: int, seed: int) -> dict[str, np.ndarray]:
    """Return disjoint train/validation/test index arrays (60%/20%/20%)."""
    development, test = train_test_split(np.arange(rows), test_size=0.2, random_state=seed)
    train, validation = train_test_split(development, test_size=0.25, random_state=seed + 1)
    result = {"train": np.sort(train), "validation": np.sort(validation), "test": np.sort(test)}
    pairs = [("train", "validation"), ("train", "test"), ("validation", "test")]
    if any(set(result[a]) & set(result[b]) for a, b in pairs):
        raise ValueError("Data splits overlap.")
    return result


def registry(seed: int) -> dict[str, Any]:
    """Build the candidate estimator library used for validation-based selection."""

    def imputer() -> SimpleImputer:
        return SimpleImputer(strategy="median", add_indicator=True)

    ridge = make_pipeline(
        imputer(), PolynomialFeatures(2, include_bias=False), StandardScaler(), Ridge(alpha=1.0)
    )
    extra = make_pipeline(
        imputer(),
        ExtraTreesRegressor(n_estimators=96, min_samples_leaf=2, random_state=seed, n_jobs=1),
    )
    forest = make_pipeline(
        imputer(),
        RandomForestRegressor(n_estimators=48, min_samples_leaf=2, random_state=seed, n_jobs=1),
    )
    stack = StackingRegressor(
        estimators=[("ridge", ridge), ("extra", extra), ("forest", forest)],
        final_estimator=make_pipeline(StandardScaler(), HuberRegressor(max_iter=1000)),
        cv=KFold(3, shuffle=True, random_state=seed),
        n_jobs=1,
    )
    return {
        "TrainingMean": make_pipeline(imputer(), DummyRegressor()),
        "RidgePolynomial": ridge,
        "ExtraTrees": extra,
        "HuberStack": stack,
    }


def feature_names(target: str) -> list[str]:
    """Return the input columns used for ``target``; DEC excludes the inlet nitrogen."""
    return [name for name in FEATURES if target != "DEC" or name != "TN_in"]


def metric(y: Any, predicted: Any) -> dict[str, float]:
    """Return R², RMSE and MAE for a set of predictions."""
    return {
        "R2": float(r2_score(y, predicted)),
        "RMSE": float(root_mean_squared_error(y, predicted)),
        "MAE": float(mean_absolute_error(y, predicted)),
    }


def fit_select(frame: pd.DataFrame, split: dict[str, np.ndarray], seed: int):
    """Select one model per target using training and validation rows only.

    Selection reads training/validation only, so the sealed test targets cannot
    influence this function. The returned models are refitted on the full
    development split once the candidate has been locked in.
    """
    train, validation = split["train"], split["validation"]
    trials: list[dict[str, Any]] = []
    selected: dict[str, str] = {}
    models: dict[str, Any] = {}
    interpretation_models: dict[str, Any] = {}
    development = np.concatenate([train, validation])
    for target in TARGETS:
        names = feature_names(target)
        fitted: dict[str, Any] = {}
        for name, estimator in registry(seed).items():
            start = time.perf_counter()
            fitted[name] = clone(estimator).fit(frame.loc[train, names], frame.loc[train, target])
            result = metric(
                frame.loc[validation, target], fitted[name].predict(frame.loc[validation, names])
            )
            trials.append(
                {
                    "target": target,
                    "model": name,
                    **result,
                    "fit_validation_seconds": time.perf_counter() - start,
                }
            )
        eligible = [
            row for row in trials if row["target"] == target and row["model"] != "TrainingMean"
        ]
        chosen = min(eligible, key=lambda row: (row["RMSE"], row["model"]))["model"]
        selected[target] = chosen
        interpretation_models[target] = fitted[chosen]
        models[target] = clone(fitted[chosen]).fit(
            frame.loc[development, names], frame.loc[development, target]
        )
    return selected, models, interpretation_models, trials


def objective(models: dict[str, Any], frame: pd.DataFrame) -> np.ndarray:
    """Evaluate both surrogate models, returning an ``(n_rows, 2)`` array."""
    return np.column_stack([models[t].predict(frame.loc[:, feature_names(t)]) for t in TARGETS])


def nondominated(values: np.ndarray) -> np.ndarray:
    """Return the indices of the non-dominated rows of a finite two-objective array."""
    if values.ndim != 2 or values.shape[1] != 2 or not np.isfinite(values).all():
        raise ValueError("Expected finite two-objective outputs.")
    best, keep = float("inf"), []
    for i in np.lexsort((values[:, 1], values[:, 0])):
        if values[i, 1] < best:
            keep.append(i)
            best = values[i, 1]
    return np.asarray(keep, int)


def build_cases(frame: pd.DataFrame, development: np.ndarray, count: int):
    """Define ``count`` synthetic scenarios with historical support rectangles.

    The PPA/DO rectangle is the intersection of a local neighbour quantile band
    and the global 5-95% range. It bounds an empirical comparison region and is
    explicitly not a device safety envelope.
    """
    train = frame.loc[development].copy()
    fill = train[FEATURES].median()
    train.loc[:, FEATURES] = train[FEATURES].fillna(fill)
    scaler = StandardScaler().fit(train[CONTEXT])
    values = scaler.transform(train[CONTEXT])
    neighbors = NearestNeighbors(n_neighbors=21).fit(values)
    indices = np.unique(np.rint(np.linspace(0, len(train) - 1, count)).astype(int))
    ordered = train.sort_values("T")
    global_low, global_high = train[ACTIONS].quantile([0.05, 0.95]).to_numpy()
    cases: list[dict[str, Any]] = []
    for _, row in ordered.iloc[indices].iterrows():
        query = scaler.transform(row[CONTEXT].to_frame().T)
        _, nearby = neighbors.kneighbors(query, n_neighbors=21)
        # Drop the exact self-match so the rectangle is defined by other records.
        local = train.iloc[nearby[0][1:]][ACTIONS]
        low = np.maximum(local.quantile(0.1).to_numpy(), global_low)
        high = np.minimum(local.quantile(0.9).to_numpy(), global_high)
        if np.any(high <= low):
            raise ValueError("Empty conditional support interval.")
        cases.append(
            {
                "date": row.Date.strftime("%Y-%m-%d"),
                "context": {key: float(row[key]) for key in FEATURES},
                "low": low.tolist(),
                "high": high.tolist(),
            }
        )
    return cases, fill


class ProxyProblem(Problem):
    """Two-objective problem over the unit square, mapped onto a support rectangle.

    The optimiser works in normalised ``[0, 1]^2`` coordinates; every raw evaluation
    is archived so the exact call budget can be checked afterwards.
    """

    def __init__(
        self, models: dict[str, Any], case: dict[str, Any], offset: np.ndarray, scale: np.ndarray
    ) -> None:
        super().__init__(n_var=2, n_obj=2, xl=np.zeros(2), xu=np.ones(2))
        self.models = models
        self.case = case
        self.offset = offset
        self.scale = scale
        self.all_u: list[np.ndarray] = []
        self.all_f: list[np.ndarray] = []

    def raw(self, unit: np.ndarray) -> np.ndarray:
        """Map normalised coordinates to PPA/DO values and evaluate both surrogates."""
        design = pd.DataFrame([self.case["context"]] * len(unit))
        low = np.asarray(self.case["low"])
        high = np.asarray(self.case["high"])
        design.loc[:, ACTIONS] = low + np.asarray(unit) * (high - low)
        return objective(self.models, design)

    def _evaluate(self, unit: np.ndarray, out: dict[str, Any], *args: Any, **kwargs: Any) -> None:
        raw = self.raw(unit)
        self.all_u.append(np.asarray(unit).copy())
        self.all_f.append(raw.copy())
        out["F"] = (raw - self.offset) / self.scale


def search_method(
    models: dict[str, Any],
    case: dict[str, Any],
    offset: np.ndarray,
    scale: np.ndarray,
    method: str,
    seed: int,
    budget: int,
) -> dict[str, Any]:
    """Run one search method on a fixed budget and summarise its Pareto archive.

    All four methods consume exactly ``budget`` surrogate evaluations, so quality
    and wall-clock time stay comparable across methods.
    """
    problem = ProxyProblem(models, case, offset, scale)
    start = time.perf_counter()
    if method == "UniformRandom":
        unit = np.random.default_rng(seed).random((budget, 2))
        raw = problem.raw(unit)
    else:
        variation = {
            "sampling": LHS(),
            "crossover": SBX(prob=0.9, eta=15),
            "mutation": PM(prob=1, prob_var=0.5, eta=20),
        }
        if method == "NSGA2":
            algorithm = NSGA2(pop_size=32, **variation)
        elif method == "SPEA2":
            algorithm = SPEA2(pop_size=32, **variation)
        elif method == "MOEAD":
            algorithm = ParallelMOEAD(
                get_reference_directions("uniform", 2, n_partitions=31),
                n_neighbors=13,
                prob_neighbor_mating=0.7,
                n_offsprings=32,
                **variation,
            )
        else:
            raise ValueError("Unknown search method.")
        minimize(problem, algorithm, ("n_eval", budget), seed=seed, verbose=False)
        unit, raw = np.vstack(problem.all_u), np.vstack(problem.all_f)
    elapsed = time.perf_counter() - start
    if len(raw) != budget:
        raise ValueError("Search method did not use the exact registered budget.")
    keep = nondominated(raw)
    front, coordinates = raw[keep], unit[keep]
    if np.any(coordinates < -1e-12) or np.any(coordinates > 1 + 1e-12):
        raise ValueError("Candidate escaped the registered support rectangle.")
    normalized = (front - offset) / scale
    hypervolume = float(HV(ref_point=HV_REFERENCE_POINT)(normalized))
    return {
        "method": method,
        "seed": seed,
        "date": case["date"],
        "n_eval": len(raw),
        "HV": hypervolume,
        "seconds": elapsed,
        "front_points": len(front),
        "front_u": coordinates.tolist(),
        "front_f": front.tolist(),
    }


def same_domain_solutions(
    models: dict[str, Any],
    cases: list[dict[str, Any]],
    records: list[dict[str, Any]],
    scale: np.ndarray,
) -> list[dict[str, Any]]:
    """Compare an NSGA-II compromise against historical and projected references.

    The same-domain reference projects the recorded inputs into the empirical
    support rectangle, so candidate and reference are evaluated under one set of
    conditions instead of being compared across different operating backgrounds.
    """
    solutions = []
    for case in cases:
        selected = [
            row for row in records if row["date"] == case["date"] and row["method"] == "NSGA2"
        ]
        unit = np.vstack([row["front_u"] for row in selected])
        values = np.vstack([row["front_f"] for row in selected])
        keep = nondominated(values)
        unit, values = unit[keep], values[keep]
        chosen = int(np.argmin(np.linalg.norm((values - values.min(axis=0)) / scale, axis=1)))
        low = np.asarray(case["low"])
        high = np.asarray(case["high"])
        historical = pd.DataFrame([case["context"]])
        anchor = historical.copy()
        original_actions = historical[ACTIONS].iloc[0].to_numpy()
        anchor.loc[:, ACTIONS] = np.clip(original_actions, low, high)[None, :]
        baseline = objective(models, historical)[0]
        projected = objective(models, anchor)[0]
        solutions.append(
            {
                "date": case["date"],
                "method": "NSGA2",
                "compromise": values[chosen].tolist(),
                "compromise_actions": (low + unit[chosen] * (high - low)).tolist(),
                "anchor_actions": anchor[ACTIONS].iloc[0].tolist(),
                "same_domain_reference": projected.tolist(),
                "historical_reference": baseline.tolist(),
                "historical_in_domain": bool(
                    np.all(original_actions >= low) and np.all(original_actions <= high)
                ),
                "delta_historical": (values[chosen] - baseline).tolist(),
                "delta_same_domain": (values[chosen] - projected).tolist(),
            }
        )
    return solutions


def run(settings: Settings, output: Path) -> dict[str, Any]:
    """Execute the full demonstration and write its evidence bundle to ``output``.

    ``output`` must not already exist, so an earlier result set can never be
    overwritten in place. On failure a ``failure.json`` recording the phase is
    written before the exception propagates.
    """
    output = output.resolve()
    output.mkdir(parents=True, exist_ok=False)
    started = time.perf_counter()
    phase = "generate"
    try:
        frame = synthetic_data(settings.rows, settings.seed)
        split = splits(len(frame), settings.seed)
        protocol = {
            "schema": "synthetic_demo_v1",
            "synthetic_only": True,
            "settings": asdict(settings),
            "targets": TARGETS,
            "continuous_input_window": "mean(x[t-1], x[t-2], x[t-3])",
            "selection": "validation RMSE; TrainingMean excluded from selection",
            "optimizer_parameters": "fixed demonstration parameters; no tuning",
            "explanation_method": "NSGA2 predeclared for same-domain examples, "
            "not selected from test results",
            "split": {key: value.tolist() for key, value in split.items()},
            "packages": {pkg: version(pkg) for pkg in ("numpy", "pandas", "scikit-learn", "pymoo")},
            "data_sha256": hashlib.sha256(
                frame.to_csv(index=False, float_format="%.17g").encode()
            ).hexdigest(),
        }
        (output / "protocol.json").write_bytes(canonical(protocol))

        phase = "fit_select"
        selected, models, interpretation, trials = fit_select(frame, split, settings.seed)
        lock = {
            "selected": selected,
            "test_used_for_selection": False,
            "protocol_sha256": sha(output / "protocol.json"),
        }
        (output / "selection_lock.json").write_bytes(canonical(lock))
        lock_hash = sha(output / "selection_lock.json")

        phase = "sealed_test"
        test_rows = split["test"]
        test = {
            target: metric(
                frame.loc[test_rows, target],
                models[target].predict(frame.loc[test_rows, feature_names(target)]),
            )
            for target in TARGETS
        }

        phase = "interpretation"
        importance: dict[str, dict[str, float]] = {}
        for target in TARGETS:
            names = feature_names(target)
            pfi = permutation_importance(
                interpretation[target],
                frame.loc[split["validation"], names],
                frame.loc[split["validation"], target],
                n_repeats=3,
                random_state=settings.seed,
                scoring="neg_root_mean_squared_error",
                n_jobs=1,
            )
            importance[target] = dict(zip(names, pfi.importances_mean.tolist(), strict=True))

        development = np.concatenate([split["train"], split["validation"]])
        cases, fill = build_cases(frame, development, settings.scenarios)
        fit_frame = frame.loc[development, FEATURES].fillna(fill)
        low, high = np.quantile(objective(models, fit_frame), [0.05, 0.95], axis=0)
        span = np.maximum(high - low, 1e-8)

        phase = "pareto_search"
        records = [
            search_method(models, case, low, span, method, seed, settings.evaluations)
            for case in cases
            for method in SEARCH_METHODS
            for seed in settings.optimizer_seeds
        ]
        solutions = same_domain_solutions(models, cases, records, span)

        summaries = []
        for method in SEARCH_METHODS:
            part = [row for row in records if row["method"] == method]
            seed_hv = [
                np.mean([row["HV"] for row in part if row["seed"] == seed])
                for seed in settings.optimizer_seeds
            ]
            timing = np.asarray([row["seconds"] for row in part])
            summaries.append(
                {
                    "method": method,
                    "HV_seed_mean": float(np.mean(seed_hv)),
                    "HV_seed_sd": float(np.std(seed_hv, ddof=1)) if len(seed_hv) > 1 else None,
                    "seconds_p50": float(np.quantile(timing, 0.5)),
                    "seconds_p95": float(np.quantile(timing, 0.95)),
                    "runs": len(part),
                    "total_evaluations": sum(row["n_eval"] for row in part),
                }
            )

        # The selection lock must still be intact after the sealed test is scored.
        assert sha(output / "selection_lock.json") == lock_hash

        result = {
            "status": "COMPLETE",
            "synthetic_only": True,
            "selected": selected,
            "test": test,
            "validation_trials": trials,
            "importance": importance,
            "search_summary": summaries,
            "cases": cases,
            "solutions": solutions,
            "runtime_seconds": time.perf_counter() - started,
            "completed_utc": datetime.now(UTC).isoformat(),
            "test_access_blocks": 1,
            "selection_lock_sha256": lock_hash,
            "scientific_scope": "synthetic workflow demonstration; no factory or causal claim",
        }
        (output / "summary.json").write_bytes(canonical(result))
        (output / "pareto.json").write_bytes(canonical(records))

        from .report import build_report

        build_report(result, records, output)

        manifest = {path.name: sha(path) for path in output.iterdir() if path.is_file()}
        (output / "manifest.json").write_bytes(canonical({"status": "COMPLETE", "files": manifest}))
        return result
    except Exception:
        (output / "failure.json").write_bytes(canonical({"status": "FAILED", "phase": phase}))
        raise
